services:
  app:
    build: .
    container_name: xoxai-server
    command: python src/main.py #uvicorn src.main:main --host 0.0.0.0 --port 80 --reload
    ports:
      - "5000:80"
    volumes:
      - ./src:/code/src
      - ./test:/code/test